// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: schedulRuleModels.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulRuleModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity      string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	RuleType      string `protobuf:"bytes,2,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	StoreIdentity string `protobuf:"bytes,3,opt,name=store_identity,json=storeIdentity,proto3" json:"store_identity,omitempty"`
	RuleDate      string `protobuf:"bytes,4,opt,name=rule_date,json=ruleDate,proto3" json:"rule_date,omitempty"`
}

func (x *SchedulRuleModel) Reset() {
	*x = SchedulRuleModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedulRuleModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulRuleModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulRuleModel) ProtoMessage() {}

func (x *SchedulRuleModel) ProtoReflect() protoreflect.Message {
	mi := &file_schedulRuleModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulRuleModel.ProtoReflect.Descriptor instead.
func (*SchedulRuleModel) Descriptor() ([]byte, []int) {
	return file_schedulRuleModels_proto_rawDescGZIP(), []int{0}
}

func (x *SchedulRuleModel) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *SchedulRuleModel) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *SchedulRuleModel) GetStoreIdentity() string {
	if x != nil {
		return x.StoreIdentity
	}
	return ""
}

func (x *SchedulRuleModel) GetRuleDate() string {
	if x != nil {
		return x.RuleDate
	}
	return ""
}

var File_schedulRuleModels_proto protoreflect.FileDescriptor

var file_schedulRuleModels_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x8f, 0x01,
	0x0a, 0x10, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x65, 0x42,
	0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schedulRuleModels_proto_rawDescOnce sync.Once
	file_schedulRuleModels_proto_rawDescData = file_schedulRuleModels_proto_rawDesc
)

func file_schedulRuleModels_proto_rawDescGZIP() []byte {
	file_schedulRuleModels_proto_rawDescOnce.Do(func() {
		file_schedulRuleModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_schedulRuleModels_proto_rawDescData)
	})
	return file_schedulRuleModels_proto_rawDescData
}

var file_schedulRuleModels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schedulRuleModels_proto_goTypes = []interface{}{
	(*SchedulRuleModel)(nil), // 0: pb.SchedulRuleModel
}
var file_schedulRuleModels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schedulRuleModels_proto_init() }
func file_schedulRuleModels_proto_init() {
	if File_schedulRuleModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schedulRuleModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedulRuleModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schedulRuleModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schedulRuleModels_proto_goTypes,
		DependencyIndexes: file_schedulRuleModels_proto_depIdxs,
		MessageInfos:      file_schedulRuleModels_proto_msgTypes,
	}.Build()
	File_schedulRuleModels_proto = out.File
	file_schedulRuleModels_proto_rawDesc = nil
	file_schedulRuleModels_proto_goTypes = nil
	file_schedulRuleModels_proto_depIdxs = nil
}
