// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: schedulDateModels.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulDateModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SchedulDateModel) Reset() {
	*x = SchedulDateModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedulDateModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulDateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulDateModel) ProtoMessage() {}

func (x *SchedulDateModel) ProtoReflect() protoreflect.Message {
	mi := &file_schedulDateModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulDateModel.ProtoReflect.Descriptor instead.
func (*SchedulDateModel) Descriptor() ([]byte, []int) {
	return file_schedulDateModels_proto_rawDescGZIP(), []int{0}
}

func (x *SchedulDateModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_schedulDateModels_proto protoreflect.FileDescriptor

var file_schedulDateModels_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x26, 0x0a,
	0x10, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schedulDateModels_proto_rawDescOnce sync.Once
	file_schedulDateModels_proto_rawDescData = file_schedulDateModels_proto_rawDesc
)

func file_schedulDateModels_proto_rawDescGZIP() []byte {
	file_schedulDateModels_proto_rawDescOnce.Do(func() {
		file_schedulDateModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_schedulDateModels_proto_rawDescData)
	})
	return file_schedulDateModels_proto_rawDescData
}

var file_schedulDateModels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schedulDateModels_proto_goTypes = []interface{}{
	(*SchedulDateModel)(nil), // 0: pb.SchedulDateModel
}
var file_schedulDateModels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schedulDateModels_proto_init() }
func file_schedulDateModels_proto_init() {
	if File_schedulDateModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schedulDateModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedulDateModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schedulDateModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schedulDateModels_proto_goTypes,
		DependencyIndexes: file_schedulDateModels_proto_depIdxs,
		MessageInfos:      file_schedulDateModels_proto_msgTypes,
	}.Build()
	File_schedulDateModels_proto = out.File
	file_schedulDateModels_proto_rawDesc = nil
	file_schedulDateModels_proto_goTypes = nil
	file_schedulDateModels_proto_depIdxs = nil
}
