// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: scheduDateService.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulDateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SchedulDateRequest) Reset() {
	*x = SchedulDateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduDateService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulDateRequest) ProtoMessage() {}

func (x *SchedulDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduDateService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulDateRequest.ProtoReflect.Descriptor instead.
func (*SchedulDateRequest) Descriptor() ([]byte, []int) {
	return file_scheduDateService_proto_rawDescGZIP(), []int{0}
}

func (x *SchedulDateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SchedulDateDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchedulDateDetail *SchedulDateModel `protobuf:"bytes,1,opt,name=SchedulDateDetail,proto3" json:"SchedulDateDetail,omitempty"`
	Code              uint32            `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *SchedulDateDetailResponse) Reset() {
	*x = SchedulDateDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduDateService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulDateDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulDateDetailResponse) ProtoMessage() {}

func (x *SchedulDateDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduDateService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulDateDetailResponse.ProtoReflect.Descriptor instead.
func (*SchedulDateDetailResponse) Descriptor() ([]byte, []int) {
	return file_scheduDateService_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulDateDetailResponse) GetSchedulDateDetail() *SchedulDateModel {
	if x != nil {
		return x.SchedulDateDetail
	}
	return nil
}

func (x *SchedulDateDetailResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_scheduDateService_proto protoreflect.FileDescriptor

var file_scheduDateService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x44, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x17, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x12, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x73, 0x0a, 0x19, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x44, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x11, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x60, 0x0a,
	0x12, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x44, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scheduDateService_proto_rawDescOnce sync.Once
	file_scheduDateService_proto_rawDescData = file_scheduDateService_proto_rawDesc
)

func file_scheduDateService_proto_rawDescGZIP() []byte {
	file_scheduDateService_proto_rawDescOnce.Do(func() {
		file_scheduDateService_proto_rawDescData = protoimpl.X.CompressGZIP(file_scheduDateService_proto_rawDescData)
	})
	return file_scheduDateService_proto_rawDescData
}

var file_scheduDateService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scheduDateService_proto_goTypes = []interface{}{
	(*SchedulDateRequest)(nil),        // 0: pb.SchedulDateRequest
	(*SchedulDateDetailResponse)(nil), // 1: pb.SchedulDateDetailResponse
	(*SchedulDateModel)(nil),          // 2: pb.SchedulDateModel
}
var file_scheduDateService_proto_depIdxs = []int32{
	2, // 0: pb.SchedulDateDetailResponse.SchedulDateDetail:type_name -> pb.SchedulDateModel
	0, // 1: pb.SchedulDateService.SchedulDateInsert:input_type -> pb.SchedulDateRequest
	1, // 2: pb.SchedulDateService.SchedulDateInsert:output_type -> pb.SchedulDateDetailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scheduDateService_proto_init() }
func file_scheduDateService_proto_init() {
	if File_scheduDateService_proto != nil {
		return
	}
	file_schedulDateModels_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scheduDateService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedulDateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduDateService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedulDateDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scheduDateService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduDateService_proto_goTypes,
		DependencyIndexes: file_scheduDateService_proto_depIdxs,
		MessageInfos:      file_scheduDateService_proto_msgTypes,
	}.Build()
	File_scheduDateService_proto = out.File
	file_scheduDateService_proto_rawDesc = nil
	file_scheduDateService_proto_goTypes = nil
	file_scheduDateService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SchedulDateServiceClient is the client API for SchedulDateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulDateServiceClient interface {
	SchedulDateInsert(ctx context.Context, in *SchedulDateRequest, opts ...grpc.CallOption) (*SchedulDateDetailResponse, error)
}

type schedulDateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulDateServiceClient(cc grpc.ClientConnInterface) SchedulDateServiceClient {
	return &schedulDateServiceClient{cc}
}

func (c *schedulDateServiceClient) SchedulDateInsert(ctx context.Context, in *SchedulDateRequest, opts ...grpc.CallOption) (*SchedulDateDetailResponse, error) {
	out := new(SchedulDateDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.SchedulDateService/SchedulDateInsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulDateServiceServer is the server API for SchedulDateService service.
type SchedulDateServiceServer interface {
	SchedulDateInsert(context.Context, *SchedulDateRequest) (*SchedulDateDetailResponse, error)
}

// UnimplementedSchedulDateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulDateServiceServer struct {
}

func (*UnimplementedSchedulDateServiceServer) SchedulDateInsert(context.Context, *SchedulDateRequest) (*SchedulDateDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchedulDateInsert not implemented")
}

func RegisterSchedulDateServiceServer(s *grpc.Server, srv SchedulDateServiceServer) {
	s.RegisterService(&_SchedulDateService_serviceDesc, srv)
}

func _SchedulDateService_SchedulDateInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulDateServiceServer).SchedulDateInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SchedulDateService/SchedulDateInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulDateServiceServer).SchedulDateInsert(ctx, req.(*SchedulDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchedulDateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SchedulDateService",
	HandlerType: (*SchedulDateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SchedulDateInsert",
			Handler:    _SchedulDateService_SchedulDateInsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduDateService.proto",
}
