// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: storeService.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffName     string `protobuf:"bytes,1,opt,name=StaffName,proto3" json:"StaffName,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Position      string `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	StoreIdentity string `protobuf:"bytes,6,opt,name=store_identity,json=storeIdentity,proto3" json:"store_identity,omitempty"`
	Identity      string `protobuf:"bytes,7,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *StaffRequest) Reset() {
	*x = StaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffRequest) ProtoMessage() {}

func (x *StaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffRequest.ProtoReflect.Descriptor instead.
func (*StaffRequest) Descriptor() ([]byte, []int) {
	return file_staffService_proto_rawDescGZIP(), []int{0}
}

func (x *StaffRequest) GetStaffName() string {
	if x != nil {
		return x.StaffName
	}
	return ""
}

func (x *StaffRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *StaffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StaffRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *StaffRequest) GetStoreIdentity() string {
	if x != nil {
		return x.StoreIdentity
	}
	return ""
}

func (x *StaffRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type StaffDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffDetail *StaffModel `protobuf:"bytes,1,opt,name=StaffDetail,proto3" json:"StaffDetail,omitempty"`
	Code        uint32      `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *StaffDetailResponse) Reset() {
	*x = StaffDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffDetailResponse) ProtoMessage() {}

func (x *StaffDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staffService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffDetailResponse.ProtoReflect.Descriptor instead.
func (*StaffDetailResponse) Descriptor() ([]byte, []int) {
	return file_staffService_proto_rawDescGZIP(), []int{1}
}

func (x *StaffDetailResponse) GetStaffDetail() *StaffModel {
	if x != nil {
		return x.StaffDetail
	}
	return nil
}

func (x *StaffDetailResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_staffService_proto protoreflect.FileDescriptor

var file_staffService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x74, 0x61, 0x66, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x11, 0x73, 0x74, 0x61, 0x66, 0x66, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x5b, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0b, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x32, 0xc3, 0x02, 0x0a,
	0x0c, 0x53, 0x74, 0x61, 0x66, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a,
	0x12, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x79, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42,
	0x0a, 0x15, 0x53, 0x74, 0x61, 0x66, 0x66, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staffService_proto_rawDescOnce sync.Once
	file_staffService_proto_rawDescData = file_staffService_proto_rawDesc
)

func file_staffService_proto_rawDescGZIP() []byte {
	file_staffService_proto_rawDescOnce.Do(func() {
		file_staffService_proto_rawDescData = protoimpl.X.CompressGZIP(file_staffService_proto_rawDescData)
	})
	return file_staffService_proto_rawDescData
}

var file_staffService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_staffService_proto_goTypes = []interface{}{
	(*StaffRequest)(nil),        // 0: pb.StaffRequest
	(*StaffDetailResponse)(nil), // 1: pb.StaffDetailResponse
	(*StaffModel)(nil),          // 2: pb.StaffModel
}
var file_staffService_proto_depIdxs = []int32{
	2, // 0: pb.StaffDetailResponse.StaffDetail:type_name -> pb.StaffModel
	0, // 1: pb.StaffService.StaffLogin:input_type -> pb.StaffRequest
	0, // 2: pb.StaffService.StaffRegister:input_type -> pb.StaffRequest
	0, // 3: pb.StaffService.StaffDetails:input_type -> pb.StaffRequest
	0, // 4: pb.StaffService.StaffDetailsModify:input_type -> pb.StaffRequest
	0, // 5: pb.StaffService.StaffPreferenceModify:input_type -> pb.StaffRequest
	1, // 6: pb.StaffService.StaffLogin:output_type -> pb.StaffDetailResponse
	1, // 7: pb.StaffService.StaffRegister:output_type -> pb.StaffDetailResponse
	1, // 8: pb.StaffService.StaffDetails:output_type -> pb.StaffDetailResponse
	1, // 9: pb.StaffService.StaffDetailsModify:output_type -> pb.StaffDetailResponse
	1, // 10: pb.StaffService.StaffPreferenceModify:output_type -> pb.StaffDetailResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_staffService_proto_init() }
func file_staffService_proto_init() {
	if File_staffService_proto != nil {
		return
	}
	file_staffModels_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_staffService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staffService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staffService_proto_goTypes,
		DependencyIndexes: file_staffService_proto_depIdxs,
		MessageInfos:      file_staffService_proto_msgTypes,
	}.Build()
	File_staffService_proto = out.File
	file_staffService_proto_rawDesc = nil
	file_staffService_proto_goTypes = nil
	file_staffService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StaffServiceClient is the client API for StaffService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StaffServiceClient interface {
	StaffLogin(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error)
	StaffRegister(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error)
	StaffDetails(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error)
	StaffDetailsModify(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error)
	StaffPreferenceModify(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error)
}

type staffServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffServiceClient(cc grpc.ClientConnInterface) StaffServiceClient {
	return &staffServiceClient{cc}
}

func (c *staffServiceClient) StaffLogin(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error) {
	out := new(StaffDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.StaffService/StaffLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) StaffRegister(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error) {
	out := new(StaffDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.StaffService/StaffRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) StaffDetails(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error) {
	out := new(StaffDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.StaffService/StaffDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) StaffDetailsModify(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error) {
	out := new(StaffDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.StaffService/StaffDetailsModify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) StaffPreferenceModify(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffDetailResponse, error) {
	out := new(StaffDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.StaffService/StaffPreferenceModify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffServiceServer is the server API for StaffService service.
type StaffServiceServer interface {
	StaffLogin(context.Context, *StaffRequest) (*StaffDetailResponse, error)
	StaffRegister(context.Context, *StaffRequest) (*StaffDetailResponse, error)
	StaffDetails(context.Context, *StaffRequest) (*StaffDetailResponse, error)
	StaffDetailsModify(context.Context, *StaffRequest) (*StaffDetailResponse, error)
	StaffPreferenceModify(context.Context, *StaffRequest) (*StaffDetailResponse, error)
}

// UnimplementedStaffServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStaffServiceServer struct {
}

func (*UnimplementedStaffServiceServer) StaffLogin(context.Context, *StaffRequest) (*StaffDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffLogin not implemented")
}
func (*UnimplementedStaffServiceServer) StaffRegister(context.Context, *StaffRequest) (*StaffDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffRegister not implemented")
}
func (*UnimplementedStaffServiceServer) StaffDetails(context.Context, *StaffRequest) (*StaffDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffDetails not implemented")
}
func (*UnimplementedStaffServiceServer) StaffDetailsModify(context.Context, *StaffRequest) (*StaffDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffDetailsModify not implemented")
}
func (*UnimplementedStaffServiceServer) StaffPreferenceModify(context.Context, *StaffRequest) (*StaffDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffPreferenceModify not implemented")
}

func RegisterStaffServiceServer(s *grpc.Server, srv StaffServiceServer) {
	s.RegisterService(&_StaffService_serviceDesc, srv)
}

func _StaffService_StaffLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).StaffLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StaffService/StaffLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).StaffLogin(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_StaffRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).StaffRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StaffService/StaffRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).StaffRegister(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_StaffDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).StaffDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StaffService/StaffDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).StaffDetails(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_StaffDetailsModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).StaffDetailsModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StaffService/StaffDetailsModify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).StaffDetailsModify(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_StaffPreferenceModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).StaffPreferenceModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StaffService/StaffPreferenceModify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).StaffPreferenceModify(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StaffService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StaffService",
	HandlerType: (*StaffServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffLogin",
			Handler:    _StaffService_StaffLogin_Handler,
		},
		{
			MethodName: "StaffRegister",
			Handler:    _StaffService_StaffRegister_Handler,
		},
		{
			MethodName: "StaffDetails",
			Handler:    _StaffService_StaffDetails_Handler,
		},
		{
			MethodName: "StaffDetailsModify",
			Handler:    _StaffService_StaffDetailsModify_Handler,
		},
		{
			MethodName: "StaffPreferenceModify",
			Handler:    _StaffService_StaffPreferenceModify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storeService.proto",
}
