// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: storeModels.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Size     uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *StoreModel) Reset() {
	*x = StoreModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreModel) ProtoMessage() {}

func (x *StoreModel) ProtoReflect() protoreflect.Message {
	mi := &file_storeModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreModel.ProtoReflect.Descriptor instead.
func (*StoreModel) Descriptor() ([]byte, []int) {
	return file_storeModels_proto_rawDescGZIP(), []int{0}
}

func (x *StoreModel) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *StoreModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreModel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StoreModel) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_storeModels_proto protoreflect.FileDescriptor

var file_storeModels_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x6a, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storeModels_proto_rawDescOnce sync.Once
	file_storeModels_proto_rawDescData = file_storeModels_proto_rawDesc
)

func file_storeModels_proto_rawDescGZIP() []byte {
	file_storeModels_proto_rawDescOnce.Do(func() {
		file_storeModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_storeModels_proto_rawDescData)
	})
	return file_storeModels_proto_rawDescData
}

var file_storeModels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storeModels_proto_goTypes = []interface{}{
	(*StoreModel)(nil), // 0: pb.StoreModel
}
var file_storeModels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storeModels_proto_init() }
func file_storeModels_proto_init() {
	if File_storeModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storeModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storeModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storeModels_proto_goTypes,
		DependencyIndexes: file_storeModels_proto_depIdxs,
		MessageInfos:      file_storeModels_proto_msgTypes,
	}.Build()
	File_storeModels_proto = out.File
	file_storeModels_proto_rawDesc = nil
	file_storeModels_proto_goTypes = nil
	file_storeModels_proto_depIdxs = nil
}
